# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-09 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='articleBody',
            fields=[
                ('articleID', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('topic', models.CharField(max_length=32)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='articleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=32)),
                ('info', models.TextField(null=True)),
                ('up', models.IntegerField()),
                ('down', models.IntegerField()),
                ('pageview', models.IntegerField()),
                ('pushData', models.DateField(auto_now=True)),
                ('articleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.articleBody')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('level', models.IntegerField()),
                ('password', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='articleinfo',
            name='authorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.users'),
        ),
    ]
